{% set name = "shadow3" %}
{% set version = "18.5.30" %}
{% set sha256 = "29289eb7710bdf51ee9603ccf4a0cc760ca15858d299a692a42c651b59c2b154" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [unix]
    - {{ compiler('m2w64_cxx') }}      # [win]
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - matplotlib
    - numpy
    - pyqt
    - scipy
    - xraylib

test:
  imports:
    - Shadow
    - Shadow.ShadowLib
    - Shadow.ShadowTools

about:
  home: https://github.com/oasys-kit/shadow3
  license: UNKNOWN
  summary: SHADOW is an open source ray tracing code for modeling optical systems
